# Generated by Django 3.1.2 on 2021-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20211201_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_new',
        ),
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='hasOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='phone',
            name='offerPrice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='processor',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='screen',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(default='', max_length=25),
        ),
    ]
