# Generated by Django 3.1.2 on 2021-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_auto_20211208_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
