# Generated by Django 3.1.2 on 2021-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0013_auto_20211208_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='phones/'),
        ),
    ]
